// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfwn94yh5tBzSnv1MuXILzPtx7HSKyOOg',
    appId: '1:1007449228833:web:407790122f527f19634560',
    messagingSenderId: '1007449228833',
    projectId: 'flutter-chat-app-15cae',
    authDomain: 'flutter-chat-app-15cae.firebaseapp.com',
    storageBucket: 'flutter-chat-app-15cae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtYceFlMBQtYwLAJ9wI6WAJcXOAZcn2JQ',
    appId: '1:1007449228833:android:b67ba4f20ca5d2be634560',
    messagingSenderId: '1007449228833',
    projectId: 'flutter-chat-app-15cae',
    storageBucket: 'flutter-chat-app-15cae.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOCCehuoUTIWaVdkqSAoLhlkwjG3b_Ek',
    appId: '1:1007449228833:ios:2cedafcceac3fac3634560',
    messagingSenderId: '1007449228833',
    projectId: 'flutter-chat-app-15cae',
    storageBucket: 'flutter-chat-app-15cae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOCCehuoUTIWaVdkqSAoLhlkwjG3b_Ek',
    appId: '1:1007449228833:ios:2cedafcceac3fac3634560',
    messagingSenderId: '1007449228833',
    projectId: 'flutter-chat-app-15cae',
    storageBucket: 'flutter-chat-app-15cae.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfwn94yh5tBzSnv1MuXILzPtx7HSKyOOg',
    appId: '1:1007449228833:web:5318aead4747a3d5634560',
    messagingSenderId: '1007449228833',
    projectId: 'flutter-chat-app-15cae',
    authDomain: 'flutter-chat-app-15cae.firebaseapp.com',
    storageBucket: 'flutter-chat-app-15cae.firebasestorage.app',
  );
}
